version: "2.1"
services:
  kometa-operations:
    image: lscr.io/linuxserver/kometa
    container_name: kometa-operations
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - KOMETA_OPERATIONS_ONLY=true
      - KOMETA_CONFIG=/config/config.yml #optional
      - KOMETA_TIME=08:00 #optional
      - KOMETA_RUN=False #optional
      - KOMETA_TEST=False #optional
      - KOMETA_NO_MISSING=False #optional
    volumes:
      - ./config:/config
    restart: unless-stopped

  kometa-overlays:
    image: lscr.io/linuxserver/kometa
    container_name: kometa-overlays
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - KOMETA_OVERLAYS_ONLY=true
      - KOMETA_CONFIG=/config/config.yml #optional
      - KOMETA_TIME=08:20 #optional
      - KOMETA_RUN=False #optional
      - KOMETA_TEST=False #optional
      - KOMETA_NO_MISSING=False #optional
    volumes:
      - ./config:/config
    restart: unless-stopped

  kometa-collections:
    image: lscr.io/linuxserver/kometa
    container_name: kometa-collections
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - KOMETA_COLLECTIONS_ONLY=true
      - KOMETA_CONFIG=/config/config.yml #optional
      - KOMETA_TIME=09:10 #optional
      - KOMETA_RUN=False #optional
      - KOMETA_TEST=False #optional
      - KOMETA_NO_MISSING=False #optional
    volumes:
      - ./config:/config
    restart: unless-stopped

#cd /your/file/path/to/Kometa
#sudo docker-compose up -d

#docker pull kometateam/kometa
#sudo docker-compose up -d

#add :develop to the image if you want to use the develop branch
