# yaml-language-server: $schema=https://raw.githubusercontent.com/Kometa-Team/Kometa/master/json-schema/config-schema.json
######################################################
#                  AWARDS 10.0                       #
######################################################

templates:
  Awards:
    optional:
      - trakt_list
    sort_title: "~_<<collection_name>>"
    sync_mode: sync
    smart_label: release.desc
    delete_not_scheduled: false
    visible_library: false
    trakt_list:
      - <<trakt_list>>

  Award:
    smart_label: release.desc
    sync_mode: sync
    sort_title: "~_<<collection_name>>"

  Award Other:
    smart_label: release.desc
    sync_mode: sync
    sort_title: "~_<<collection_name>>"
    visible_library: true

# Films ayant remporté certains des prix les plus prestigieux
collections:
  BAFTA - Best Film:
    template: { name: Awards }
    summary: Les British Academy Film Awards sont une cérémonie annuelle organisée par la British Academy of Film and Television Arts (BAFTA) pour récompenser les meilleures contributions britanniques et internationales au cinéma. Les cérémonies se tenaient initialement dans le cinéma Odeon phare à Leicester Square, Londres, avant de se dérouler à la Royal Opera House.
    file_poster: config/posters/BAFTA Best Film.png
    visible_shared: monthly(27)
    imdb_award:
      event_id: "ev0000123"
      event_year: "1949-current"
      winning: true
      catergory_filter: "Best Film"
      type: "movie,tv_movie"
      language: "en"
      sort_by: release.desc
      limit: 9999

  BAFTA - Winners:
    template: { name: Awards }
    summary: Les British Academy Film Awards sont une cérémonie annuelle organisée par la British Academy of Film and Television Arts (BAFTA) pour récompenser les meilleures contributions britanniques et internationales au cinéma. Les cérémonies se tenaient initialement dans le cinéma Odeon phare à Leicester Square, Londres, avant de se dérouler à la Royal Opera House.
    visible_shared: monthly(3)
    file_poster: config/posters/BAFTA Winners.png
    imdb_award:
      event_id: "ev0000123"
      event_year: "1949-current"
      winning: true
      type: "movie,tv_movie"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Berlinale - Winners:
    template: { name: Award }
    summary: Le Festival international du film de Berlin, également connu sous le nom de Berlinale, est l'un des plus grands et prestigieux festivals de cinéma au monde. Il se tient chaque année à Berlin, en Allemagne, et présente un large éventail de films internationaux.
    visible_library: true
    file_poster: config/posters/Berlinale Winners.png
    letterboxd_list: https://letterboxd.com/koyoti/list/berlinale-golden-bear-winners/

  Cannes - Palme d'Or:
    template: { name: Awards }
    summary: Le Festival de Cannes, jusqu'en 2003 appelé le Festival international du film, est un festival de cinéma annuel qui se tient à Cannes, en France, et présente des films de tous genres, y compris des documentaires, venus du monde entier. Créé en 1946, ce festival sur invitation est organisé chaque année au Palais des Festivals et des Congrès. Il a été accrédité officiellement par la FIAPF en 1951.
    visible_shared: monthly(17)
    file_poster: config/posters/Cannes Palme d'or.png
    imdb_award:
      event_id: "ev0000147"
      event_year: "1955-current"
      winning: true
      award_filter: "Palme d'Or"
      type: "movie,tv_movie"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Critics Choice Awards - Winners:
    template: { name: Awards }
    summary: Les Critics' Choice Movie Awards (anciennement connus sous le nom de Broadcast Film Critics Association Award) sont une cérémonie annuelle présentée par la Critics Choice Association américano-canadienne pour récompenser les meilleures réalisations cinématographiques.
    visible_shared: monthly(14)
    file_poster: config/posters/Critics Choice Awards Winners.png
    imdb_award:
      event_id: "ev0000133"
      event_year: "1996-current"
      winning: true
      type: "movie,tv_movie"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Golden Globe - Best Picture:
    template: { name: Awards }
    summary: Les Golden Globe Awards sont des distinctions décernées par la Hollywood Foreign Press Association depuis janvier 1944, reconnaissant l'excellence dans les films et la télévision, tant américains qu'internationaux. Depuis 2022, l'HFPA compte 105 membres.
    visible_shared:
      - monthly(23)
      - monthly(24)
    file_poster: config/posters/Golden Globe Best Picture.png
    imdb_award:
      event_id: "ev0000292"
      event_year: "1944-current"
      winning: true
      category_filter:
        - Best Picture
        - Best Motion Picture - Drama
        - Best Motion Picture - Comedy or Musical
        - Best Motion Picture - Animated
        - Best Motion Picture - Non-English Language
      type: "movie,tv_movie"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Golden Globe - Winners:
    template: { name: Awards }
    summary: Les Golden Globe Awards sont des distinctions décernées par la Hollywood Foreign Press Association depuis janvier 1944, reconnaissant l'excellence dans les films et la télévision, tant américains qu'internationaux. Depuis 2022, l'HFPA compte 105 membres.
    visible_shared:
      - monthly(17)
      - monthly(18)
    file_poster: config/posters/Golden Globe Winners.png
    imdb_award:
      event_id: "ev0000292"
      event_year: "1944-current"
      winning: true
      type: "movie,tv_movie"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Oscars - Best Picture:
    template: { name: Awards }
    visible_library: true
    visible_shared:
      - monthly(21)
      - monthly(22)
    summary: La plus haute distinction des Oscars.
    file_poster: config/posters/Oscars Best Picture.png
    imdb_award:
      event_id: "ev0000003"
      event_year: "1929-current"
      winning: true
      category_filter:
        - Best Picture
        - Best Motion Picture of the Year
      type: "movie,tv_movie"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Oscars - Winners:
    template: { name: Awards }
    visible_library: true
    visible_shared:
      - monthly(30)
      - monthly(31)
    file_poster: config/posters/Oscars Winners.png
    summary: Films ayant remporté une catégorie aux Oscars.
    imdb_award:
      event_id: "ev0000003"
      event_year: "1929-current"
      winning: true
      language: "en"
      sort_by: release.desc
      limit: 9999

  Sundance - Winners:
    template: { name: imdb }
    summary: Une liste de tous les films (à quelques exceptions près, comme les courts-métrages) ayant remporté un prix au festival américain de Sundance.
    visible_shared: monthly(11)
    file_poster: config/posters/Sundance Winners.png
    imdb_award:
      event_id: "ev0000631"
      event_year: "1978-current"
      winning: true
      type: "movie,tv_movie"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Venice - Best Film:
    template: { name: Awards }
    summary: Le Festival international du film de Venise est un festival annuel qui se tient à Venise, en Italie. Il s'agit du plus ancien festival de cinéma au monde et fait partie des six plus grands festivals internationaux de cinéma, avec les trois grands festivals européens, le Festival de Toronto au Canada, le Festival de Sundance aux États-Unis et le Festival de Melbourne en Australie.
    visible_shared: monthly(9)
    file_poster: config/posters/Venice Best Film.png
    imdb_award:
      event_id: "ev0000681"
      event_year: "1932-current"
      winning: true
      category_filter:
        - Best Film
        - Golden Lion
      type: "movie,tv_movie"
      language: "en"
      sort_by: release.desc
      limit: 9999
