# yaml-language-server: $schema=https://raw.githubusercontent.com/Kometa-Team/Kometa/master/json-schema/config-schema.json
######################################################
#                   SPECIALS 18.0                    #
######################################################
templates:
  Special:
    smart_label: random
    sync_mode: sync
    sort_title: "~~~~~~~~~-<<collection_name>>"

  Special Smart:
    sync_mode: sync
    sort_title: "~~~~~~~~~-<<collection_name>>"
    visible_library: true

  Special Other:
    smart_label: random
    sync_mode: sync
    sort_title: "~~~~~~~~~-<<collection_name>>"
    visible_library: true

  Special Smart Other:
    sync_mode: sync
    sort_title: "~~~~~~~~~-<<collection_name>>"
    visible_library: false

collections:        
  2160P:
    template: { name: Special }
    summary: Une collection de films en 4K.
    file_poster: config/posters/2160P.png
    plex_search:
      all:
        resolution: 4K

  DV/HDR: 
    template: { name: Special }
    summary: Une collection de films en HDR10+ et Dolby Vision.
    file_poster: config/posters/DV-HDR.png
    plex_search:
      all:
        hdr: true

  En famille:
    template: { name: Special Other }
    summary: Des films adaptés pour les familles, reconnus pour leur qualité et leur impact. Sélections incluant des médias appropriés pour susciter des conversations en famille.
    visible_shared: monthly(25)
    file_poster: config/posters/Family Friendly.png
    trakt_list: https://trakt.tv/users/k0meta/lists/common-sense-selection-movies

  Favoris:
    template: { name: Special Smart Other }
    tautulli_popular:
      list_days: 31
      list_size: 20
      list_minimum: 1
    tautulli_watched:
      list_days: 31
      list_size: 20
      list_minimum: 1
    smart_label: viewed.desc
    file_poster: config/posters/Favored.png
    summary: Les films les plus appréciés sur Plex par les utilisateurs le mois dernier.

  Les plus longs:
    template: { name: Special Smart Other }
    file_poster: config/posters/Longest.png
    summary: Les films les plus longs sur Plex, d'une durée minimale de 150 minutes.
    smart_filter:
      sort_by: duration.desc
      validate: false
      all:
        duration.gt: 149

  Les plus courts:
    template: { name: Special Smart }
    visible_library: true
    summary: Les films les plus courts sur Plex, d'une durée maximale de 85 minutes.
    file_poster: config/posters/Shortest.png
    smart_filter:
      sort_by: duration.asc
      validate: false
      all:
        duration.lt: 85
        genre.not: Animation

  Vus:
    template: { name: Special Smart Other }
    tautulli_watched:
      list_days: 9999
      list_size: 9999
      list_minimum: 1
    file_poster: config/posters/Watched.png
    summary: Films regardés sur Plex par tous les utilisateurs.
    smart_label: viewed.desc
