######################################################
#                SEPARATORS 5.0                      #
######################################################

templates:
  Separator:
    blank_collection: true

# Creates a separator to make it more clear where a category of collection starts and ends
collections:
  # Chart Collections:
    # template: { name: Separator }
    # sort_title: "!_!"
    # #summary: Chart collections up next.
    # file_poster: config/posters/Chart Collections.png

  Sélections spéciales fêtes:
    template: { name: Separator }
    sort_title: "!!_!"
    #summary: Holiday collections up next.
    file_poster: config/posters/Holiday Collections.png

  Par plateforme de streaming:
    template: { name: Separator }
    sort_title: "!!!_!"
    #summary: Streaming collections up next.
    file_poster: config/posters/Streaming Collections.png

  Par genre:
    template: { name: Separator }
    sort_title: "!!!!_!"
    #summary: Genre collections up next.
    file_poster: config/posters/Genre Collections.png

  Par sous-genres:
    template: { name: Separator }
    sort_title: "!!!!!_!"
    #summary: Subgenre collections up next.
    file_poster: config/posters/Subgenre Collections.png

  Par récompenses et prix:
    template: { name: Separator }
    sort_title: "~_!"
    #summary: Award collections up next.
    file_poster: config/posters/Award Collections.png
    
  Par acteur:
    template: { name: Separator }
    sort_title: "~~_!"
    #summary: Actor collections up next.
    file_poster: config/posters/Actor Collections.png

  Par réalisateur:
    template: { name: Separator }
    sort_title: "~~~_!"
    #summary: Director collections up next.
    file_poster: config/posters/Director Collections.png

  Par écrivains:
    template: { name: Separator }
    sort_title: "~~~~_!"
    #summary: Author collections up next.
    file_poster: config/posters/Author Collections.png

  Par studio:
    template: { name: Separator }
    sort_title: "~~~~~_!"
    #summary: Studio collections up next.
    file_poster: config/posters/Studio Collections.png

  Par franchise:
    template: { name: Separator }
    sort_title: "~~~~~~_!"
    #summary: Franchise collections up next.
    file_poster: config/posters/Franchise Collections.png

  Par décénnie:
    template: { name: Separator }
    sort_title: "~~~~~~~_!"
    #summary: Decade collections up next.
    file_poster: config/posters/Decade Collections.png

  Par année:
    template: { name: Separator }
    sort_title: "~~~~~~~~_!"
    #summary: Year collections up next.
    file_poster: config/posters/Year Collections.png

  Autres:
    template: { name: Separator }
    sort_title: "~~~~~~~~~_!"
    #summary: Special collections up next.
    file_poster: config/posters/Special Collections.png
