######################################################
#                   SPECIALS 18.0                    #
######################################################
templates:
  Special:
    smart_label: random
    sync_mode: sync
    sort_title: zz-<<collection_name>>

  Special Smart:
    sync_mode: sync
    sort_title: zz-<<collection_name>>
    visible_library: true

  Special Other:
    smart_label: random
    sync_mode: sync
    sort_title: zz-<<collection_name>>
    visible_library: true

  Special Smart Other:
    sync_mode: sync
    sort_title: zz-<<collection_name>>
    visible_library: false

collections:        
  2160P:
    template: { name: Special }
    summary: A collection of movies in 4K.
    file_poster: config/posters/2160P.png
    plex_search:
      all:
        resolution: 4K

  DV/HDR: # 1080p or 4K movies with HDR and or Dolby Vision
    template: { name: Special }
    summary: A collection of movies in HDR10+ and Dolby Vision.
    file_poster: config/posters/DV-HDR.png
    plex_search:
      all:
        hdr: true

  Family Friendly: # Better suited movies for family watching
    template: { name: Special Other }
    summary: Family Friendly recognizes outstanding entertainment with an official seal for quality and impact. Age Approved Selections include age-appropriate media with the potential to spark family conversations.
    visible_shared: monthly(25)
    file_poster: config/posters/Family Friendly.png
    trakt_list: https://trakt.tv/users/k0meta/lists/common-sense-selection-movies

  Favored: # Fetched information from Tautulli
    template: { name: Special Smart Other }
    tautulli_popular:
      list_days: 31
      list_size: 20
      list_minimum: 1
    tautulli_watched:
      list_days: 31
      list_size: 20
      list_minimum: 1
    smart_label: viewed.desc
    file_poster: config/posters/Favored.png
    summary: The most favored Movies on Plex by users the past month.

  Longest: # Longest movies on plex
    template: { name: Special Smart Other }
    file_poster: config/posters/Longest.png
    summary: The longest movies on Plex  a minimum of 150 minutes in duration.
    smart_filter:
      sort_by: duration.desc
      validate: false
      all:
        duration.gt: 149

  Les plus courts:
    template: { name: Special Smart }
    visible_library: true
    summary: The shortest movies on Plex with a max duration of 85 minutes and under.
    file_poster: config/posters/Shortest.png
    smart_filter:
      sort_by: duration.asc
      validate: false
      all:
        duration.lt: 85
        genre.not: Animation

  Watched: # Fetched information from Tautulli
    template: { name: Special Smart Other }
    tautulli_watched:
      list_days: 9999
      list_size: 9999
      list_minimum: 1
    file_poster: config/posters/Watched.png
    summary: Movies watched on Plex by all users.
    smart_label: viewed.desc
