#############################################################
#                       AWARDS 9.5                          #
#############################################################

templates:
  imdb:
    optional:
      - trakt_list
    sort_title: "zzz_<<collection_name>>"
    sync_mode: sync
    smart_label: release.desc
    visible_library: true
    delete_not_scheduled: false
    trakt_list:
      - <<trakt_list>>

# Séries qui ont remporté certains des prix les plus prestigieux
collections:
  BAFTA - Winners:
    template: { name: imdb }
    summary: "A collection of BAFTA Winners"
    visible_shared: monthly(10)
    visible_library: false
    file_poster: config/posters/BAFTA Winners.png
    imdb_award:
      event_id: "ev0000123"
      event_year: "1949-current"
      winning: true
      type: "tv_series,tv_special,tv_mini_series"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Critics Choice Awards - Winners:
    template: { name: imdb }
    summary: "A collection of Critics Choice Award Winners"
    visible_shared: monthly(5)
    visible_library: false
    file_poster: config/posters/Critics Choice Awards Winners.png
    imdb_award:
      event_id: "ev0000133"
      event_year: "1996-current"
      winning: true
      type: "tv_series,tv_special,tv_mini_series"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Emmy - Winners:
    template: { name: imdb }
    summary: "A collection of Emmy Award Winners"
    visible_shared: monthly(20)
    file_poster: config/posters/Emmy Winners.png
    imdb_award:
      event_id: "ev0000223"
      event_year: "1949-current"
      winning: true
      type: "tv_series,tv_special,tv_mini_series"
      language: "en"
      sort_by: release.desc
      limit: 9999

  Golden Globe - Winners:
    template: { name: imdb }
    summary: "A collection of Golden Globes Winners"
    visible_shared: monthly(15)
    file_poster: config/posters/Golden Globe Winners.png
    imdb_award:
      event_id: "ev0000292"
      event_year: "1944-current"
      winning: true
      type: "tv_series,tv_special,tv_mini_series"
      language: "en"
      sort_by: release.desc
      limit: 9999
