######################################################
#                   SPECIALS 17.0                    #
######################################################

templates:
  Rating:
    collection_order: custom
    sync_mode: sync

  Special:
    smart_label: random
    sync_mode: sync
    sort_title: zz__<<collection_name>>
    visible_library: true

  Special Plus:
    smart_label: random
    sync_mode: sync
    sort_title: zz__<<collection_name>>
    visible_library: false

  Special Smart:
    sync_mode: sync
    sort_title: zz__<<collection_name>>
    visible_library: true

  Special Smart Other:
    sync_mode: sync
    sort_title: zz__<<collection_name>>
    visible_library: false

collections:
  18+: # TV shows with an adult rating
    template: { name: Special Smart }
    visible_shared: monthly(9)
    summary: Les séries avec cette classification ne conviennent généralement pas aux enfants ou aux personnes de moins de 17 ans (certaines sources peuvent indiquer 18 ans). Ce contenu est destiné à un public mature en raison de thèmes adultes tels que la violence, la violence sexuelle, un langage fort, la nudité, les substances, le tabagisme et le sexe.
    file_poster: config/posters/18+.png
    sort_title: zz__118+
    smart_filter:
      sort_by: random
      limit: 200
      validate: false
      all:
        content_rating: TV-MA

  480P+: # Séries TV en qualité 480p et 576p
    template: { name: Special Plus }
    summary: Une collection de séries TV en qualité SD, 480p et 576p.
    sort_title: zz__1480P+
    file_poster: config/posters/480P+.png
    plex_search:
      any:
        resolution:
          - SD
          - 480p
          - 576p

  720P:
    template: { name: Special Plus }
    summary: Une collection de séries TV en qualité 720p.
    sort_title: zz__1720P
    file_poster: config/posters/720P.png
    plex_search:
      all:
        resolution: 720p

  1080P:
    template: { name: Special Plus }
    summary: Une collection de séries TV en qualité 1080p.
    sort_title: zz__31080P
    file_poster: config/posters/1080P.png
    plex_search:
      all:
        resolution: 1080p

  2160P:
    template: { name: Special }
    summary: Une collection de séries TV en 4K.
    sort_title: zz__42160P
    file_poster: config/posters/2160P.png
    plex_search:
      all:
        resolution: 4K

  DV/HDR: # Films 1080p ou 4K avec HDR et/ou Dolby Vision
    template: { name: Special }
    summary: Une collection de séries TV en HDR10+ et Dolby Vision.
    file_poster: config/posters/DV-HDR.png
    plex_search:
      all:
        hdr: true

  Family Friendly: # Better suited movies for family watching
    template: { name: Special }
    summary: Family Friendly recognizes outstanding entertainment with an official seal for quality and impact. Age Approved Selections include age-appropriate media with the potential to spark family conversations.
    file_poster: config/posters/Family Friendly.png
    visible_shared: monthly(10)
    trakt_list: https://trakt.tv/users/k0meta/lists/common-sense-selection-shows

  Favored: # Fetched information from Tautulli
    template: { name: Special Smart Other }
    tautulli_popular:
      list_days: 62
      list_size: 20
      list_minimum: 1
    tautulli_watched:
      list_days: 62
      list_size: 20
      list_minimum: 1
    smart_label: viewed.desc
    file_poster: config/posters/Favored.png
    summary: The most favored TV shows on Plex by users the past 2 months.

  Longest: # Longest TV shows on plex
    template: { name: Special Plus }
    summary: The lengthiest shows on Plex.
    file_poster: config/posters/Longest.png
    trakt_list:
      - https://trakt.tv/users/belamarlua/lists/long-shows-i-watched-more-then-one-time?sort=rank,asc
      - https://trakt.tv/users/copeland1994/lists/all-time-series-rankings-long-running-shows-only?sort=rank,asc

  Vues: # Informations recueillies à partir de Tautulli
    template: { name: Special Smart Other }
    tautulli_watched:
      list_days: 9999
      list_size: 9999
      list_minimum: 1
    file_poster: config/posters/Watched.png
    summary: Shows watched on Plex by all users.
    smart_label: viewed.desc
