# yaml-language-server: $schema=https://raw.githubusercontent.com/Kometa-Team/Kometa/master/json-schema/config-schema.json
######################################################
#                   SPECIALS 17.0                    #
######################################################

templates:
  Special:
    smart_label: random
    sync_mode: sync
    sort_title: "~~~~~~_<<collection_name>>"
    visible_library: true

  Special Plus:
    smart_label: random
    sync_mode: sync
    sort_title: "~~~~~~_<<collection_name>>"
    visible_library: false

  Special Smart:
    sync_mode: sync
    sort_title: "~~~~~~_<<collection_name>>"
    visible_library: true

  Special Smart Other:
    sync_mode: sync
    sort_title: "~~~~~~_<<collection_name>>"
    visible_library: false

collections:
  18+: # Séries TV avec une classification adulte
    template: { name: Special Smart }
    visible_shared: monthly(9)
    summary: Les séries avec cette classification ne conviennent généralement pas aux enfants ou aux personnes de moins de 17 ans (certaines sources peuvent indiquer 18 ans). Ce contenu est destiné à un public mature en raison de thèmes adultes tels que la violence, la violence sexuelle, un langage fort, la nudité, les substances, le tabagisme et le sexe.
    file_poster: config/posters/18+.png
    sort_title: zz__118+
    smart_filter:
      sort_by: random
      limit: 200
      validate: false
      all:
        content_rating: TV-MA

  480P+: # Séries TV en qualité 480p et 576p
    template: { name: Special Plus }
    summary: Une collection de séries TV en qualité SD, 480p et 576p.
    sort_title: zz__1480P+
    file_poster: config/posters/480P+.png
    plex_search:
      any:
        resolution:
          - SD
          - 480p
          - 576p

  720P:
    template: { name: Special Plus }
    summary: Une collection de séries TV en qualité 720p.
    sort_title: zz__1720P
    file_poster: config/posters/720P.png
    plex_search:
      all:
        resolution: 720p

  1080P:
    template: { name: Special Plus }
    summary: Une collection de séries TV en qualité 1080p.
    sort_title: zz__31080P
    file_poster: config/posters/1080P.png
    plex_search:
      all:
        resolution: 1080p

  2160P:
    template: { name: Special }
    summary: Une collection de séries TV en 4K.
    sort_title: zz__42160P
    file_poster: config/posters/2160P.png
    plex_search:
      all:
        resolution: 4K

  DV/HDR: # Films 1080p ou 4K avec HDR et/ou Dolby Vision
    template: { name: Special }
    summary: Une collection de séries TV en HDR10+ et Dolby Vision.
    file_poster: config/posters/DV-HDR.png
    plex_search:
      all:
        hdr: true

  En famille: # Films mieux adaptés pour la famille
    template: { name: Special }
    summary: Des séries adaptées pour les familles, reconnues pour leur qualité et leur impact. Sélections incluant des médias appropriés pour susciter des conversations en famille.
    file_poster: config/posters/Family Friendly.png
    visible_shared: monthly(10)
    trakt_list: https://trakt.tv/users/k0meta/lists/common-sense-selection-shows

  Favoris: # Informations recueillies à partir de Tautulli
    template: { name: Special Smart Other }
    tautulli_popular:
      list_days: 62
      list_size: 20
      list_minimum: 1
    tautulli_watched:
      list_days: 62
      list_size: 20
      list_minimum: 1
    smart_label: viewed.desc
    file_poster: config/posters/Favored.png
    summary: Les séries TV les plus appréciées sur Plex par les utilisateurs au cours des 2 derniers mois.

  Les plus longues: # Séries TV les plus longues sur Plex
    template: { name: Special Plus }
    summary: Les séries les plus longues sur Plex.
    file_poster: config/posters/Longest.png
    trakt_list:
      - https://trakt.tv/users/andrewh4352/lists/top-shows-long-running?sort=rank,asc
      - https://trakt.tv/users/copeland1994/lists/all-time-series-rankings-long-running-shows-only?sort=rank,asc

  Vues: # Informations recueillies à partir de Tautulli
    template: { name: Special Smart Other }
    tautulli_watched:
      list_days: 9999
      list_size: 9999
      list_minimum: 1
    file_poster: config/posters/Watched.png
    summary: Séries regardées sur Plex par tous les utilisateurs.
    smart_label: viewed.desc
