# Change the library names below to your exact(!) plex library names.
libraries:
  Films:
    collection_files:
    - file: config/3-Movies_General.yml
    - file: config/3-Movies_Separators.yml
    - file: config/3-Movies_Holidays
    - file: config/3-Movies_Studios.yml
    - file: config/3-Movies_Genres.yml
    - file: config/3-Movies_Awards.yml
    - file: config/3-Movies_People.yml
    - file: config/3-Movies_Franchises.yml
    - file: config/3-Movies_Specials.yml
    - file: config/3-Movies_Years.yml
    operations:
    - delete_collections:
        # configured: false
        managed: true
    - mass_genre_update:
      - unlock
      - tmdb
      - imdb
    - mass_audience_rating_update: imdb
    overlay_files:
    - file: config/3.1-Movies_Overlays_4K.yml
    - file: config/3.1-Movies_Overlays_Rating.yml
      # - file: config/3.1-Movies_Overlays_Subtitle.yml
    - file: config/3.1-Movies_Overlays_Top.yml
  Séries TV:
    collection_files:
    - file: config/7-TV_General.yml
    - file: config/7-TV_Separators.yml
    - file: config/7-TV_Networks.yml
    - file: config/7-TV_Genres.yml
    - file: config/7-TV_Awards.yml
    - file: config/7-TV_Franchises.yml
    - file: config/7-TV_Years.yml
    - file: config/7-TV_Specials.yml
    operations:
    - delete_collections:
        # configured: false
        managed: true
    - mass_genre_update:
      - unlock
      - tmdb
      - imdb
    - mass_audience_rating_update: imdb
    overlay_files:
    - file: config/7.1-TV_Overlays_4K.yml
    - file: config/7.1-TV_Overlays_Canceled.yml
    - file: config/7.1-TV_Overlays_Rating.yml
    - file: config/7.1-TV_Overlays_Top.yml
settings:
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_users: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
  overlay_artwork_filetype: jpg
  overlay_artwork_quality:
webhooks: # Can be individually specified per library as well
  error:
  version:
  run_start:
  run_end:
  changes:
  delete:
plex:                                # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://192.168.2.2:32400
  token: <REDACTED>
  timeout: 60
  db_cache:
  clean_bundles: false
  empty_trash: false
  optimize: false
  verify_ssl:
tmdb:                                # REQUIRED for the script to run
  apikey: <REDACTED>
  language: fr
  cache_expiration: 60
  region:
tautulli:                            # Can be individually specified per library as well
  url: http://192.168.2.2:8181
  apikey: <REDACTED>
github:
  token: <REDACTED>
omdb:
  apikey: <REDACTED>
  cache_expiration: 60
mdblist:
  apikey: <REDACTED>
  cache_expiration: 60
radarr:                              # Can be individually specified per library as well
  url: http://192.168.2.2:7878
  token: <REDACTED>
  addadd_missing: false
  add_existing: false
  upgrade_existing: false
  monitor_existing: false
  root_folder_path: F:\movies
  monitor: true
  availability: announced
  quality_profile: UHD Bluray + WEB
  tag:
  search: false
  radarr_path:
  plex_path:
  ignore_cache: false
  add_missing: false
sonarr:                              # Can be individually specified per library as well
  url: http://192.168.2.2:8989
  token: <REDACTED>
  add_missing: false
  add_existing: false
  upgrade_existing: false
  monitor_existing: false
  root_folder_path: G:\tv
  monitor: all
  quality_profile: WEB-2160p
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:
  ignore_cache: false
  language_profile:
trakt:
  client_id: <REDACTED>
  client_secret: <REDACTED>
  pin:
  authorization:
    # everything below is autofilled by the script
    access_token: <REDACTED>
    token_type: Bearer
    expires_in: 7889238
    refresh_token: <REDACTED>
    scope: public
    created_at: 1728658574
